/**
 * OpenCode v2 TUI keybind catalog (built-in defaults).
 *
 * Source of truth (researched 2026-09 from opencode-source):
 *   packages/tui/src/config/keybind.ts → Definitions (snake_case) + CommandMap (dotted ids)
 * User config keys use dotted command ids in ~/.config/opencode/cli.json → keybinds.
 */

import type { KeymapGroup, KeymapItem } from "../../types";
import { l10n } from "../../i18n";

export const OPENCODE_KEYBIND_CATALOG: readonly KeymapItem[] = [
  {
    id: "leader",
    group: "general" as KeymapGroup,
    title: "Leader key",
    desc: "Prefix key for key sequences; press it, then the next key",
    def: "ctrl+x",
  },
  {
    id: "app.exit",
    group: "general" as KeymapGroup,
    title: "Exit application",
    desc: "Exit OpenCode",
    def: "ctrl+c,ctrl+d,<leader>q",
  },
  {
    id: "app.debug",
    group: "general" as KeymapGroup,
    title: "Debug panel",
    desc: "Toggle the debug panel",
    def: "none",
  },
  {
    id: "app.console",
    group: "general" as KeymapGroup,
    title: "Console",
    desc: "Toggle the console",
    def: "none",
  },
  {
    id: "app.heap_snapshot",
    group: "general" as KeymapGroup,
    title: "Heap snapshot",
    desc: "Write a heap snapshot",
    def: "none",
  },
  {
    id: "app.toggle.animations",
    group: "general" as KeymapGroup,
    title: "Toggle animations",
    desc: "Turn interface animations on or off",
    def: "none",
  },
  {
    id: "app.toggle.file_context",
    group: "general" as KeymapGroup,
    title: "Toggle file context",
    desc: "Show or hide file context",
    def: "none",
  },
  {
    id: "app.toggle.diffwrap",
    group: "general" as KeymapGroup,
    title: "Toggle diff wrap",
    desc: "Turn diff line wrapping on or off",
    def: "none",
  },
  {
    id: "app.toggle.paste_summary",
    group: "general" as KeymapGroup,
    title: "Toggle paste summary",
    desc: "Show or hide pasted content summary",
    def: "none",
  },
  {
    id: "app.toggle.session_directory_filter",
    group: "general" as KeymapGroup,
    title: "Toggle directory filter",
    desc: "Filter the session list by directory",
    def: "none",
  },
  {
    id: "command.palette.show",
    group: "general" as KeymapGroup,
    title: "Command palette",
    desc: "Show all available commands",
    def: "ctrl+p",
  },
  {
    id: "help.show",
    group: "general" as KeymapGroup,
    title: "Help",
    desc: "Open the help dialog",
    def: "none",
  },
  {
    id: "docs.open",
    group: "general" as KeymapGroup,
    title: "Open docs",
    desc: "Open the OpenCode documentation",
    def: "none",
  },
  {
    id: "theme.switch",
    group: "general" as KeymapGroup,
    title: "Switch theme",
    desc: "List and switch themes",
    def: "<leader>t",
  },
  {
    id: "theme.switch_mode",
    group: "general" as KeymapGroup,
    title: "Light/dark mode",
    desc: "Switch between light and dark themes",
    def: "none",
  },
  {
    id: "theme.mode.lock",
    group: "general" as KeymapGroup,
    title: "Lock theme mode",
    desc: "Lock or unlock the theme mode",
    def: "none",
  },
  {
    id: "session.sidebar.toggle",
    group: "general" as KeymapGroup,
    title: "Sidebar",
    desc: "Toggle the sidebar",
    def: "<leader>b",
  },
  {
    id: "session.toggle.scrollbar",
    group: "general" as KeymapGroup,
    title: "Session scrollbar",
    desc: "Toggle the session scrollbar",
    def: "none",
  },
  {
    id: "opencode.status",
    group: "general" as KeymapGroup,
    title: "Status",
    desc: "Show OpenCode status",
    def: "<leader>s",
  },
  {
    id: "opencode.debug",
    group: "general" as KeymapGroup,
    title: "Debug info",
    desc: "Show debug information",
    def: "none",
  },
  {
    id: "terminal.suspend",
    group: "general" as KeymapGroup,
    title: "Suspend terminal",
    desc: "Suspend the terminal (forcibly disabled on Windows)",
    def: "ctrl+z",
  },
  {
    id: "terminal.title.toggle",
    group: "general" as KeymapGroup,
    title: "Terminal title",
    desc: "Toggle the terminal title",
    def: "none",
  },
  {
    id: "tips.toggle",
    group: "general" as KeymapGroup,
    title: "Tips",
    desc: "Toggle home screen tips",
    def: "<leader>h",
  },
  {
    id: "plugins.list",
    group: "general" as KeymapGroup,
    title: "Manage plugins",
    desc: "Open the plugin manager dialog",
    def: "none",
  },
  {
    id: "plugins.install",
    group: "general" as KeymapGroup,
    title: "Install plugin",
    desc: "Install a plugin",
    def: "none",
  },
  {
    id: "session.new",
    group: "session" as KeymapGroup,
    title: "New session",
    desc: "Create a new session",
    def: "<leader>n",
  },
  {
    id: "session.list",
    group: "session" as KeymapGroup,
    title: "Session list",
    desc: "List all sessions",
    def: "<leader>l",
  },
  {
    id: "session.timeline",
    group: "session" as KeymapGroup,
    title: "Session timeline",
    desc: "Show the session timeline",
    def: "<leader>g",
  },
  {
    id: "session.export",
    group: "session" as KeymapGroup,
    title: "Export session",
    desc: "Export the session to an editor",
    def: "<leader>x",
  },
  {
    id: "session.copy",
    group: "session" as KeymapGroup,
    title: "Copy session",
    desc: "Copy the session transcript",
    def: "none",
  },
  {
    id: "session.move",
    group: "session" as KeymapGroup,
    title: "Move session",
    desc: "Move the session to another project",
    def: "none",
  },
  {
    id: "session.fork",
    group: "session" as KeymapGroup,
    title: "Fork session",
    desc: "Fork the session from a message",
    def: "none",
  },
  {
    id: "session.rename",
    group: "session" as KeymapGroup,
    title: "Rename session",
    desc: "Rename the current session",
    def: "ctrl+r",
  },
  {
    id: "session.delete",
    group: "session" as KeymapGroup,
    title: "Delete session",
    desc: "Delete the current session",
    def: "ctrl+d",
  },
  {
    id: "session.share",
    group: "session" as KeymapGroup,
    title: "Share session",
    desc: "Share the current session",
    def: "none",
  },
  {
    id: "session.unshare",
    group: "session" as KeymapGroup,
    title: "Unshare session",
    desc: "Stop sharing the session",
    def: "none",
  },
  {
    id: "session.interrupt",
    group: "session" as KeymapGroup,
    title: "Interrupt session",
    desc: "Interrupt the current run",
    def: "escape",
  },
  {
    id: "session.background",
    group: "session" as KeymapGroup,
    title: "Background subagent",
    desc: "Send the sync subagent to the background",
    def: "ctrl+b",
  },
  {
    id: "session.compact",
    group: "session" as KeymapGroup,
    title: "Compact session",
    desc: "Compact the session context",
    def: "<leader>c",
  },
  {
    id: "session.toggle.timestamps",
    group: "session" as KeymapGroup,
    title: "Timestamps",
    desc: "Toggle message timestamps",
    def: "none",
  },
  {
    id: "session.toggle.generic_tool_output",
    group: "session" as KeymapGroup,
    title: "Tool output",
    desc: "Toggle generic tool output display",
    def: "none",
  },
  {
    id: "session.queued_prompts",
    group: "session" as KeymapGroup,
    title: "Queued prompts",
    desc: "Manage queued prompts",
    def: "<leader>q",
  },
  {
    id: "session.child.first",
    group: "session" as KeymapGroup,
    title: "First child session",
    desc: "Jump to the first child session",
    def: "<leader>down",
  },
  {
    id: "session.child.next",
    group: "session" as KeymapGroup,
    title: "Next child session",
    desc: "Switch to the next child session",
    def: "right",
  },
  {
    id: "session.child.previous",
    group: "session" as KeymapGroup,
    title: "Previous child session",
    desc: "Switch to the previous child session",
    def: "left",
  },
  {
    id: "session.parent",
    group: "session" as KeymapGroup,
    title: "Parent session",
    desc: "Return to the parent session",
    def: "up",
  },
  {
    id: "session.pin.toggle",
    group: "session" as KeymapGroup,
    title: "Pin session",
    desc: "Pin or unpin in the session list",
    def: "ctrl+f",
  },
  {
    id: "session.quick_switch.1",
    group: "session" as KeymapGroup,
    title: "Quick switch 1",
    desc: "Switch to quick slot 1",
    def: "<leader>1",
  },
  {
    id: "session.quick_switch.2",
    group: "session" as KeymapGroup,
    title: "Quick switch 2",
    desc: "Switch to quick slot 2",
    def: "<leader>2",
  },
  {
    id: "session.quick_switch.3",
    group: "session" as KeymapGroup,
    title: "Quick switch 3",
    desc: "Switch to quick slot 3",
    def: "<leader>3",
  },
  {
    id: "session.quick_switch.4",
    group: "session" as KeymapGroup,
    title: "Quick switch 4",
    desc: "Switch to quick slot 4",
    def: "<leader>4",
  },
  {
    id: "session.quick_switch.5",
    group: "session" as KeymapGroup,
    title: "Quick switch 5",
    desc: "Switch to quick slot 5",
    def: "<leader>5",
  },
  {
    id: "session.quick_switch.6",
    group: "session" as KeymapGroup,
    title: "Quick switch 6",
    desc: "Switch to quick slot 6",
    def: "<leader>6",
  },
  {
    id: "session.quick_switch.7",
    group: "session" as KeymapGroup,
    title: "Quick switch 7",
    desc: "Switch to quick slot 7",
    def: "<leader>7",
  },
  {
    id: "session.quick_switch.8",
    group: "session" as KeymapGroup,
    title: "Quick switch 8",
    desc: "Switch to quick slot 8",
    def: "<leader>8",
  },
  {
    id: "session.quick_switch.9",
    group: "session" as KeymapGroup,
    title: "Quick switch 9",
    desc: "Switch to quick slot 9",
    def: "<leader>9",
  },
  {
    id: "stash.delete",
    group: "session" as KeymapGroup,
    title: "Delete stash",
    desc: "Delete the stash entry",
    def: "ctrl+d",
  },
  {
    id: "session.page.up",
    group: "nav" as KeymapGroup,
    title: "Page up",
    desc: "Scroll the message area up one page",
    def: "pageup,ctrl+alt+b",
  },
  {
    id: "session.page.down",
    group: "nav" as KeymapGroup,
    title: "Page down",
    desc: "Scroll the message area down one page",
    def: "pagedown,ctrl+alt+f",
  },
  {
    id: "session.line.up",
    group: "nav" as KeymapGroup,
    title: "Line up",
    desc: "Scroll the message area up one line",
    def: "ctrl+alt+y",
  },
  {
    id: "session.line.down",
    group: "nav" as KeymapGroup,
    title: "Line down",
    desc: "Scroll the message area down one line",
    def: "ctrl+alt+e",
  },
  {
    id: "session.half.page.up",
    group: "nav" as KeymapGroup,
    title: "Half page up",
    desc: "Scroll the message area up half a page",
    def: "ctrl+alt+u",
  },
  {
    id: "session.half.page.down",
    group: "nav" as KeymapGroup,
    title: "Half page down",
    desc: "Scroll the message area down half a page",
    def: "ctrl+alt+d",
  },
  {
    id: "session.first",
    group: "nav" as KeymapGroup,
    title: "First message",
    desc: "Jump to the first message",
    def: "ctrl+g,home",
  },
  {
    id: "session.last",
    group: "nav" as KeymapGroup,
    title: "Last message",
    desc: "Jump to the last message",
    def: "ctrl+alt+g,end",
  },
  {
    id: "session.message.next",
    group: "nav" as KeymapGroup,
    title: "Next message",
    desc: "Jump to the next message",
    def: "none",
  },
  {
    id: "session.message.previous",
    group: "nav" as KeymapGroup,
    title: "Previous message",
    desc: "Jump to the previous message",
    def: "none",
  },
  {
    id: "session.messages_last_user",
    group: "nav" as KeymapGroup,
    title: "Last user message",
    desc: "Jump to the last user message",
    def: "none",
  },
  {
    id: "messages.copy",
    group: "nav" as KeymapGroup,
    title: "Copy message",
    desc: "Copy the current message",
    def: "<leader>y",
  },
  {
    id: "session.undo",
    group: "nav" as KeymapGroup,
    title: "Undo message",
    desc: "Undo the previous message",
    def: "<leader>u",
  },
  {
    id: "session.redo",
    group: "nav" as KeymapGroup,
    title: "Redo message",
    desc: "Redo the message",
    def: "<leader>r",
  },
  {
    id: "session.toggle.conceal",
    group: "nav" as KeymapGroup,
    title: "Collapse code blocks",
    desc: "Toggle code block collapsing in messages",
    def: "<leader>h",
  },
  {
    id: "session.toggle.actions",
    group: "nav" as KeymapGroup,
    title: "Tool details",
    desc: "Toggle tool call details",
    def: "none",
  },
  {
    id: "session.toggle.thinking",
    group: "nav" as KeymapGroup,
    title: "Thinking",
    desc: "Toggle thinking block display",
    def: "none",
  },
  {
    id: "model.list",
    group: "model" as KeymapGroup,
    title: "Model list",
    desc: "List available models",
    def: "<leader>m",
  },
  {
    id: "model.dialog.provider",
    group: "model" as KeymapGroup,
    title: "Provider list",
    desc: "Open providers in the model dialog",
    def: "ctrl+a",
  },
  {
    id: "model.dialog.favorite",
    group: "model" as KeymapGroup,
    title: "Favorite model",
    desc: "Toggle favorite in the model dialog",
    def: "ctrl+f",
  },
  {
    id: "model.cycle_recent",
    group: "model" as KeymapGroup,
    title: "Recent model",
    desc: "Switch to a recently used model",
    def: "f2",
  },
  {
    id: "model.cycle_recent_reverse",
    group: "model" as KeymapGroup,
    title: "Recent model (reverse)",
    desc: "Cycle recent models in reverse",
    def: "shift+f2",
  },
  {
    id: "model.cycle_favorite",
    group: "model" as KeymapGroup,
    title: "Cycle favorites",
    desc: "Cycle through favorite models",
    def: "none",
  },
  {
    id: "model.cycle_favorite_reverse",
    group: "model" as KeymapGroup,
    title: "Cycle favorites (reverse)",
    desc: "Cycle favorite models in reverse",
    def: "none",
  },
  {
    id: "mcp.list",
    group: "model" as KeymapGroup,
    title: "MCP list",
    desc: "List MCP servers",
    def: "none",
  },
  {
    id: "provider.connect",
    group: "model" as KeymapGroup,
    title: "Connect provider",
    desc: "Connect a model provider",
    def: "none",
  },
  {
    id: "console.org.switch",
    group: "model" as KeymapGroup,
    title: "Switch organization",
    desc: "Switch the Console organization",
    def: "none",
  },
  {
    id: "agent.list",
    group: "model" as KeymapGroup,
    title: "Agent list",
    desc: "List available agents",
    def: "<leader>a",
  },
  {
    id: "agent.cycle",
    group: "model" as KeymapGroup,
    title: "Next agent",
    desc: "Switch to the next agent",
    def: "tab",
  },
  {
    id: "agent.cycle.reverse",
    group: "model" as KeymapGroup,
    title: "Previous agent",
    desc: "Switch to the previous agent",
    def: "shift+tab",
  },
  {
    id: "variant.cycle",
    group: "model" as KeymapGroup,
    title: "Cycle variant",
    desc: "Switch the model variant",
    def: "ctrl+t",
  },
  {
    id: "variant.list",
    group: "model" as KeymapGroup,
    title: "Variant list",
    desc: "List model variants",
    def: "none",
  },
  {
    id: "prompt.editor",
    group: "input" as KeymapGroup,
    title: "External editor",
    desc: "Open the prompt in an external editor",
    def: "<leader>e",
  },
  {
    id: "prompt.submit",
    group: "input" as KeymapGroup,
    title: "Submit prompt",
    desc: "Submit the current prompt (standalone command)",
    def: "none",
  },
  {
    id: "prompt.clear",
    group: "input" as KeymapGroup,
    title: "Clear input",
    desc: "Clear the input box",
    def: "ctrl+c",
  },
  {
    id: "prompt.paste",
    group: "input" as KeymapGroup,
    title: "Paste",
    desc: "Paste from the clipboard",
    def: "ctrl+v",
  },
  {
    id: "prompt.editor_context.clear",
    group: "input" as KeymapGroup,
    title: "Clear editor context",
    desc: "Clear the editor context",
    def: "none",
  },
  {
    id: "prompt.skills",
    group: "input" as KeymapGroup,
    title: "Skill picker",
    desc: "Open the skill picker",
    def: "none",
  },
  {
    id: "prompt.stash",
    group: "input" as KeymapGroup,
    title: "Stash prompt",
    desc: "Stash the current prompt",
    def: "none",
  },
  {
    id: "prompt.stash.pop",
    group: "input" as KeymapGroup,
    title: "Pop stash",
    desc: "Pop the stashed prompt",
    def: "none",
  },
  {
    id: "prompt.stash.list",
    group: "input" as KeymapGroup,
    title: "Stash list",
    desc: "List stashed prompts",
    def: "none",
  },
  {
    id: "workspace.set",
    group: "input" as KeymapGroup,
    title: "Set workspace",
    desc: "Set the workspace",
    def: "none",
  },
  {
    id: "prompt.history.previous",
    group: "input" as KeymapGroup,
    title: "Previous history",
    desc: "Previous input history entry",
    def: "up",
  },
  {
    id: "prompt.history.next",
    group: "input" as KeymapGroup,
    title: "Next history",
    desc: "Next input history entry",
    def: "down",
  },
  {
    id: "input.submit",
    group: "input" as KeymapGroup,
    title: "Send",
    desc: "Submit the input",
    def: "return",
  },
  {
    id: "input.newline",
    group: "input" as KeymapGroup,
    title: "Newline",
    desc: "Insert a newline in the input box",
    def: "shift+return,ctrl+return,alt+return,ctrl+j",
  },
  {
    id: "input.move.left",
    group: "input" as KeymapGroup,
    title: "Cursor left",
    desc: "Move the input cursor left",
    def: "left,ctrl+b",
  },
  {
    id: "input.move.right",
    group: "input" as KeymapGroup,
    title: "Cursor right",
    desc: "Move the input cursor right",
    def: "right,ctrl+f",
  },
  {
    id: "input.move.up",
    group: "input" as KeymapGroup,
    title: "Cursor up",
    desc: "Move the input cursor up",
    def: "up",
  },
  {
    id: "input.move.down",
    group: "input" as KeymapGroup,
    title: "Cursor down",
    desc: "Move the input cursor down",
    def: "down",
  },
  {
    id: "input.select.left",
    group: "input" as KeymapGroup,
    title: "Select left",
    desc: "Extend the selection left",
    def: "shift+left",
  },
  {
    id: "input.select.right",
    group: "input" as KeymapGroup,
    title: "Select right",
    desc: "Extend the selection right",
    def: "shift+right",
  },
  {
    id: "input.select.up",
    group: "input" as KeymapGroup,
    title: "Select up",
    desc: "Extend the selection up",
    def: "shift+up",
  },
  {
    id: "input.select.down",
    group: "input" as KeymapGroup,
    title: "Select down",
    desc: "Extend the selection down",
    def: "shift+down",
  },
  {
    id: "input.line.home",
    group: "input" as KeymapGroup,
    title: "Line start",
    desc: "Move to the start of the line",
    def: "ctrl+a",
  },
  {
    id: "input.line.end",
    group: "input" as KeymapGroup,
    title: "Line end",
    desc: "Move to the end of the line",
    def: "ctrl+e",
  },
  {
    id: "input.select.line.home",
    group: "input" as KeymapGroup,
    title: "Select to line start",
    desc: "Select up to the line start",
    def: "ctrl+shift+a",
  },
  {
    id: "input.select.line.end",
    group: "input" as KeymapGroup,
    title: "Select to line end",
    desc: "Select up to the line end",
    def: "ctrl+shift+e",
  },
  {
    id: "input.visual.line.home",
    group: "input" as KeymapGroup,
    title: "Visual line start",
    desc: "Move to the visual line start",
    def: "alt+a",
  },
  {
    id: "input.visual.line.end",
    group: "input" as KeymapGroup,
    title: "Visual line end",
    desc: "Move to the visual line end",
    def: "alt+e",
  },
  {
    id: "input.select.visual.line.home",
    group: "input" as KeymapGroup,
    title: "Select to visual line start",
    desc: "Select up to the visual line start",
    def: "alt+shift+a",
  },
  {
    id: "input.select.visual.line.end",
    group: "input" as KeymapGroup,
    title: "Select to visual line end",
    desc: "Select up to the visual line end",
    def: "alt+shift+e",
  },
  {
    id: "input.buffer.home",
    group: "input" as KeymapGroup,
    title: "Buffer start",
    desc: "Move to the start of the buffer",
    def: "home",
  },
  {
    id: "input.buffer.end",
    group: "input" as KeymapGroup,
    title: "Buffer end",
    desc: "Move to the end of the buffer",
    def: "end",
  },
  {
    id: "input.select.buffer.home",
    group: "input" as KeymapGroup,
    title: "Select to buffer start",
    desc: "Select up to the buffer start",
    def: "shift+home",
  },
  {
    id: "input.select.buffer.end",
    group: "input" as KeymapGroup,
    title: "Select to buffer end",
    desc: "Select up to the buffer end",
    def: "shift+end",
  },
  {
    id: "input.delete.line",
    group: "input" as KeymapGroup,
    title: "Delete line",
    desc: "Delete the entire line",
    def: "ctrl+shift+d",
  },
  {
    id: "input.delete.to.line.end",
    group: "input" as KeymapGroup,
    title: "Delete to line end",
    desc: "Delete up to the line end",
    def: "ctrl+k",
  },
  {
    id: "input.delete.to.line.start",
    group: "input" as KeymapGroup,
    title: "Delete to line start",
    desc: "Delete up to the line start",
    def: "ctrl+u",
  },
  {
    id: "input.backspace",
    group: "input" as KeymapGroup,
    title: "Backspace",
    desc: "Delete the previous character",
    def: "backspace,shift+backspace",
  },
  {
    id: "input.delete",
    group: "input" as KeymapGroup,
    title: "Delete",
    desc: "Delete the character at the cursor",
    def: "ctrl+d,delete,shift+delete",
  },
  {
    id: "input.undo",
    group: "input" as KeymapGroup,
    title: "Undo input",
    desc: "Undo input (ctrl+z also bound on Windows)",
    def: "ctrl+-,super+z",
  },
  {
    id: "input.redo",
    group: "input" as KeymapGroup,
    title: "Redo input",
    desc: "Redo the input",
    def: "ctrl+.,super+shift+z",
  },
  {
    id: "input.word.forward",
    group: "input" as KeymapGroup,
    title: "Word forward",
    desc: "Move the cursor forward one word",
    def: "alt+f,alt+right,ctrl+right",
  },
  {
    id: "input.word.backward",
    group: "input" as KeymapGroup,
    title: "Word backward",
    desc: "Move the cursor backward one word",
    def: "alt+b,alt+left,ctrl+left",
  },
  {
    id: "input.select.word.forward",
    group: "input" as KeymapGroup,
    title: "Select next word",
    desc: "Select up to the next word",
    def: "alt+shift+f,alt+shift+right",
  },
  {
    id: "input.select.word.backward",
    group: "input" as KeymapGroup,
    title: "Select previous word",
    desc: "Select up to the previous word",
    def: "alt+shift+b,alt+shift+left",
  },
  {
    id: "input.delete.word.forward",
    group: "input" as KeymapGroup,
    title: "Delete next word",
    desc: "Delete the next word",
    def: "alt+d,alt+delete,ctrl+delete",
  },
  {
    id: "input.delete.word.backward",
    group: "input" as KeymapGroup,
    title: "Delete previous word",
    desc: "Delete the previous word",
    def: "ctrl+w,ctrl+backspace,alt+backspace",
  },
  {
    id: "input.select.all",
    group: "input" as KeymapGroup,
    title: "Select all",
    desc: "Select all input content",
    def: "super+a",
  },
  {
    id: "dialog.select.prev",
    group: "dialog" as KeymapGroup,
    title: "Previous item",
    desc: "Previous item in the dialog",
    def: "up,ctrl+p",
  },
  {
    id: "dialog.select.next",
    group: "dialog" as KeymapGroup,
    title: "Next item",
    desc: "Next item in the dialog",
    def: "down,ctrl+n",
  },
  {
    id: "dialog.select.page_up",
    group: "dialog" as KeymapGroup,
    title: "Page up",
    desc: "Scroll the dialog up one page",
    def: "pageup",
  },
  {
    id: "dialog.select.page_down",
    group: "dialog" as KeymapGroup,
    title: "Page down",
    desc: "Scroll the dialog down one page",
    def: "pagedown",
  },
  {
    id: "dialog.select.home",
    group: "dialog" as KeymapGroup,
    title: "First item",
    desc: "Jump to the first dialog item",
    def: "home",
  },
  {
    id: "dialog.select.end",
    group: "dialog" as KeymapGroup,
    title: "Last item",
    desc: "Jump to the last dialog item",
    def: "end",
  },
  {
    id: "dialog.select.submit",
    group: "dialog" as KeymapGroup,
    title: "Confirm selection",
    desc: "Submit the dialog selection",
    def: "return",
  },
  {
    id: "dialog.prompt.submit",
    group: "dialog" as KeymapGroup,
    title: "Confirm input",
    desc: "Submit the dialog input",
    def: "return",
  },
  {
    id: "dialog.mcp.toggle",
    group: "dialog" as KeymapGroup,
    title: "Toggle MCP",
    desc: "Toggle in the MCP dialog",
    def: "space",
  },
  {
    id: "dialog.move_session.new",
    group: "dialog" as KeymapGroup,
    title: "New project copy",
    desc: "Move session: create a new project copy",
    def: "ctrl+m",
  },
  {
    id: "dialog.move_session.delete",
    group: "dialog" as KeymapGroup,
    title: "Delete project copy",
    desc: "Move session: delete a project copy",
    def: "ctrl+d",
  },
  {
    id: "dialog.move_session.refresh",
    group: "dialog" as KeymapGroup,
    title: "Refresh project copies",
    desc: "Move session: refresh the list",
    def: "ctrl+r",
  },
  {
    id: "prompt.autocomplete.prev",
    group: "dialog" as KeymapGroup,
    title: "Previous completion",
    desc: "Previous autocomplete suggestion",
    def: "up,ctrl+p",
  },
  {
    id: "prompt.autocomplete.next",
    group: "dialog" as KeymapGroup,
    title: "Next completion",
    desc: "Next autocomplete suggestion",
    def: "down,ctrl+n",
  },
  {
    id: "prompt.autocomplete.hide",
    group: "dialog" as KeymapGroup,
    title: "Hide completions",
    desc: "Hide the autocomplete suggestions",
    def: "escape",
  },
  {
    id: "prompt.autocomplete.select",
    group: "dialog" as KeymapGroup,
    title: "Select completion",
    desc: "Select the autocomplete suggestion",
    def: "return",
  },
  {
    id: "prompt.autocomplete.complete",
    group: "dialog" as KeymapGroup,
    title: "Complete",
    desc: "Apply the completion",
    def: "tab",
  },
  {
    id: "permission.prompt.fullscreen",
    group: "dialog" as KeymapGroup,
    title: "Fullscreen permission prompt",
    desc: "Toggle fullscreen permission prompts",
    def: "ctrl+f",
  },
  {
    id: "plugins.toggle",
    group: "dialog" as KeymapGroup,
    title: "Toggle plugin",
    desc: "Toggle in the plugin dialog",
    def: "space",
  },
  {
    id: "dialog.plugins.install",
    group: "dialog" as KeymapGroup,
    title: "Install plugin",
    desc: "Install from the plugin dialog",
    def: "shift+i",
  },
  {
    id: "diff.open",
    group: "diff" as KeymapGroup,
    title: "Open diff",
    desc: "Open the diff viewer",
    def: "none",
  },
  {
    id: "diff.close",
    group: "diff" as KeymapGroup,
    title: "Close diff",
    desc: "Close the diff viewer",
    def: "escape,q",
  },
  {
    id: "diff.toggle",
    group: "diff" as KeymapGroup,
    title: "Expand/collapse",
    desc: "Toggle a diff entry",
    def: "enter,space",
  },
  {
    id: "diff.expand",
    group: "diff" as KeymapGroup,
    title: "Expand",
    desc: "Expand a diff entry",
    def: "right",
  },
  {
    id: "diff.expand_all",
    group: "diff" as KeymapGroup,
    title: "Expand all",
    desc: "Expand all diff folders",
    def: "E",
  },
  {
    id: "diff.collapse",
    group: "diff" as KeymapGroup,
    title: "Collapse",
    desc: "Collapse a diff entry",
    def: "left",
  },
  {
    id: "diff.switch_focus",
    group: "diff" as KeymapGroup,
    title: "Switch focus",
    desc: "Switch focus in the diff viewer",
    def: "tab",
  },
  {
    id: "diff.next_hunk",
    group: "diff" as KeymapGroup,
    title: "Next hunk",
    desc: "Jump to the next diff hunk",
    def: "]",
  },
  {
    id: "diff.previous_hunk",
    group: "diff" as KeymapGroup,
    title: "Previous hunk",
    desc: "Jump to the previous diff hunk",
    def: "[",
  },
  {
    id: "diff.next_file",
    group: "diff" as KeymapGroup,
    title: "Next file",
    desc: "Jump to the next diff file",
    def: "n",
  },
  {
    id: "diff.previous_file",
    group: "diff" as KeymapGroup,
    title: "Previous file",
    desc: "Jump to the previous diff file",
    def: "p",
  },
  {
    id: "diff.toggle_file_tree",
    group: "diff" as KeymapGroup,
    title: "File tree",
    desc: "Toggle the diff file tree",
    def: "b",
  },
  {
    id: "diff.single_patch",
    group: "diff" as KeymapGroup,
    title: "Single patch view",
    desc: "Toggle the single patch view",
    def: "s",
  },
  {
    id: "diff.switch_source",
    group: "diff" as KeymapGroup,
    title: "Switch source",
    desc: "Switch the diff source",
    def: "d",
  },
  {
    id: "diff.toggle_view",
    group: "diff" as KeymapGroup,
    title: "Toggle view",
    desc: "Toggle split/unified view",
    def: "v",
  },
  {
    id: "diff.help",
    group: "diff" as KeymapGroup,
    title: "Diff help",
    desc: "Show diff viewer shortcuts",
    def: "?",
  },
  {
    id: "which-key.toggle",
    group: "whichkey" as KeymapGroup,
    title: "Which-key panel",
    desc: "Toggle the which-key panel",
    def: "ctrl+alt+k",
  },
  {
    id: "which-key.layout.toggle",
    group: "whichkey" as KeymapGroup,
    title: "Toggle layout",
    desc: "Toggle the which-key layout",
    def: "ctrl+alt+shift+k",
  },
  {
    id: "which-key.pending.toggle",
    group: "whichkey" as KeymapGroup,
    title: "Pending preview",
    desc: "Toggle the which-key pending preview",
    def: "ctrl+alt+shift+p",
  },
  {
    id: "which-key.group.previous",
    group: "whichkey" as KeymapGroup,
    title: "Previous group",
    desc: "Previous which-key group",
    def: "ctrl+alt+left,ctrl+alt+[",
  },
  {
    id: "which-key.group.next",
    group: "whichkey" as KeymapGroup,
    title: "Next group",
    desc: "Next which-key group",
    def: "ctrl+alt+right,ctrl+alt+]",
  },
  {
    id: "which-key.scroll.up",
    group: "whichkey" as KeymapGroup,
    title: "Scroll up",
    desc: "Scroll the which-key panel up",
    def: "ctrl+alt+up,ctrl+alt+p",
  },
  {
    id: "which-key.scroll.down",
    group: "whichkey" as KeymapGroup,
    title: "Scroll down",
    desc: "Scroll the which-key panel down",
    def: "ctrl+alt+down,ctrl+alt+n",
  },
  {
    id: "which-key.page.up",
    group: "whichkey" as KeymapGroup,
    title: "Page up",
    desc: "Page the which-key panel up",
    def: "ctrl+alt+pageup",
  },
  {
    id: "which-key.page.down",
    group: "whichkey" as KeymapGroup,
    title: "Page down",
    desc: "Page the which-key panel down",
    def: "ctrl+alt+pagedown",
  },
  {
    id: "which-key.home",
    group: "whichkey" as KeymapGroup,
    title: "Jump to start",
    desc: "Jump to the first which-key item",
    def: "ctrl+alt+home",
  },
  {
    id: "which-key.end",
    group: "whichkey" as KeymapGroup,
    title: "Jump to end",
    desc: "Jump to the last which-key item",
    def: "ctrl+alt+end",
  },
];

export function findKeymapItem(id: string): KeymapItem | undefined {
  return OPENCODE_KEYBIND_CATALOG.find((item) => item.id === id);
}

/**
 * Catalog entries with localized title/desc for display in the webview.
 * Ids, groups, and default bindings are never localized.
 */
export function localizeKeymapItems(
  items: readonly KeymapItem[],
): KeymapItem[] {
  return items.map((item) => ({
    ...item,
    title: l10n.t(item.title),
    desc: l10n.t(item.desc),
  }));
}
